# Generated by Django 3.2 on 2021-05-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.TextField(max_length=200)),
                ('projectDescription', models.TextField(max_length=500)),
                ('projectUrl', models.URLField(max_length=1000)),
                ('postDate', models.DateField()),
            ],
        ),
    ]
