# Generated by Django 3.2 on 2021-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('postDate', models.DateField()),
                ('postTime', models.TimeField()),
            ],
        ),
    ]
