# Generated by Django 3.2 on 2021-05-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('image1', models.ImageField(upload_to='static/home/gallery')),
                ('image1Title', models.TextField(max_length=50)),
                ('image1Subtitle', models.TextField(max_length=100)),
                ('image1Text', models.TextField(max_length=500)),
                ('image2', models.ImageField(upload_to='static/home/gallery')),
                ('image2Title', models.TextField(max_length=50)),
                ('image2Subtitle', models.TextField(max_length=100)),
                ('image2Text', models.TextField(max_length=500)),
                ('image3', models.ImageField(upload_to='static/home/gallery')),
                ('image3Title', models.TextField(max_length=50)),
                ('image3Subtitle', models.TextField(max_length=100)),
                ('image3Text', models.TextField(max_length=500)),
                ('image4', models.ImageField(upload_to='static/home/gallery')),
                ('image4Title', models.TextField(max_length=50)),
                ('image4Subtitle', models.TextField(max_length=100)),
                ('image4Text', models.TextField(max_length=500)),
                ('image5', models.ImageField(upload_to='static/home/gallery')),
                ('image5Title', models.TextField(max_length=50)),
                ('image5Subtitle', models.TextField(max_length=100)),
                ('image5Text', models.TextField(max_length=500)),
                ('image6', models.ImageField(upload_to='static/home/gallery')),
                ('image6Title', models.TextField(max_length=50)),
                ('image6Subtitle', models.TextField(max_length=100)),
                ('image6Text', models.TextField(max_length=500)),
                ('postDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=25)),
                ('text', models.TextField(max_length=150)),
                ('postDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TopSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName1Title', models.TextField(max_length=20)),
                ('skillName1Description', models.TextField(max_length=200)),
                ('skillName2Title', models.TextField(max_length=20)),
                ('skillName2Description', models.TextField(max_length=200)),
                ('skillName3Title', models.TextField(max_length=20)),
                ('skillName3Description', models.TextField(max_length=200)),
                ('postDate', models.DateField()),
            ],
        ),
    ]
