# Generated by Django 3.2 on 2021-05-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name_plural': 'ImageGallery'},
        ),
        migrations.AlterModelOptions(
            name='tagline',
            options={'verbose_name_plural': 'Tagline'},
        ),
        migrations.AlterModelOptions(
            name='topskills',
            options={'verbose_name_plural': 'TopSkills'},
        ),
    ]
