# Generated by Django 3.2 on 2021-05-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210510_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='image1Subtitle',
            new_name='imageSubtitle',
        ),
        migrations.RenameField(
            model_name='imagegallery',
            old_name='image1Text',
            new_name='imageText',
        ),
        migrations.RenameField(
            model_name='imagegallery',
            old_name='image1Title',
            new_name='imageTitle',
        ),
        migrations.RenameField(
            model_name='imagegallery',
            old_name='image1',
            new_name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image2Subtitle',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image2Text',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image2Title',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image3Subtitle',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image3Text',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image3Title',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image4Subtitle',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image4Text',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image4Title',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image5Subtitle',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image5Text',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image5Title',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image6Subtitle',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image6Text',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='image6Title',
        ),
    ]
