# Generated by Django 3.2 on 2021-05-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210513_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='text',
        ),
    ]
