# Generated by Django 3.2 on 2021-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.TextField(max_length=100)),
                ('imageUrl', models.ImageField(upload_to='about/image')),
                ('postDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvTitle', models.TextField(max_length=100)),
                ('attachement', models.FileField(upload_to='about/cv')),
                ('postDate', models.DateField()),
            ],
        ),
    ]
