# Generated by Django 3.2 on 2021-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_abouttext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('githubLink', models.URLField()),
                ('linkedinLink', models.URLField()),
                ('postDate', models.DateField()),
            ],
        ),
    ]
