# Generated by Django 3.2 on 2021-05-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimage',
            options={'verbose_name_plural': 'About Image'},
        ),
        migrations.AlterModelOptions(
            name='abouttext',
            options={'verbose_name_plural': 'About Text'},
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name_plural': 'CV'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name_plural': 'Social Links'},
        ),
    ]
